chapter.create.requested=5
chapter.text.processed=5
chapter.words.saved=5
chapter.creation.completed=5
chapter.creation.error=5

finance.bill.created=1
finance.bill.payment=1
finance.bill.paid=1
finance.bill.confirmed=1
finance.bill.refunded=1
finance.bill.error=1

finance.usage.created=1
finance.usage.cancelled=1
finance.usage.error=1

finance.transaction.startbonus=1
finance.transaction.created=1
finance.transaction.error=1
