name: lare_tests
services:
  db:
    image: postgres:latest
    container_name: lare_test_db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5435:5432"
    volumes:
      - test_pg_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: lare_test_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: lare_test_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: lare_test_kafka_ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  app:
    build:
      context: ..
      dockerfile: tests_env/app/Dockerfile
    container_name: lare_test_app
    depends_on:
      - db
      - kafka
    environment:
      DATABASE_URL: postgres://test:test@db:5432/test_db
    ports:
      - "8088:8000"

  test_runner:
    build:
      context: ..
      dockerfile: tests_env/test_runner/Dockerfile
    container_name: lare_test_runner
    depends_on:
      - app
    environment:
      BASE_URL: http://app:8000
    command: ["sh", "./run_tests.sh"]

  locust:
    container_name: lare_test_locust
    build:
      context: ..
      dockerfile: tests_env/locust/Dockerfile
    working_dir: /locust
    environment:
      PYTHONPATH: /locust
    ports:
      - "8089:8089"
    volumes: []

volumes:
  test_pg_data:
